# Generated by Django 5.0.1 on 2026-01-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0005_siteconfig_account_name_siteconfig_account_number_and_more'),
        ('parent', '0001_initial'),
        ('students', '0004_alter_student_options_remove_student_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentloginlog',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='students.guardian'),
        ),
        migrations.AddField(
            model_name='parentnotification',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.guardian'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('student', 'term')},
        ),
    ]
