# Generated by Django 5.0 on 2026-01-31 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
        ('staffs', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianPaymentSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Invoiced')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Paid')),
                ('total_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Balance')),
                ('total_invoices', models.IntegerField(default=0, verbose_name='Total Invoices')),
                ('paid_invoices', models.IntegerField(default=0, verbose_name='Paid Invoices')),
                ('overdue_invoices', models.IntegerField(default=0, verbose_name='Overdue Invoices')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_invoice_date', models.DateField(blank=True, null=True, verbose_name='Last Invoice Date')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Last Payment Date')),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_summary', to='students.guardian', verbose_name='Guardian')),
            ],
            options={
                'verbose_name': 'Guardian Payment Summary',
                'verbose_name_plural': 'Guardian Payment Summaries',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Invoice Number')),
                ('description', models.TextField(verbose_name='Description')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid')),
                ('balance', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Balance')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('partially_paid', 'Partially Paid')], default='active', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bank_deposit', 'Bank Deposit'), ('pos', 'POS'), ('online', 'Online Payment'), ('remita', 'Remita'), ('cheque', 'Cheque')], max_length=50, verbose_name='Payment Method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff', verbose_name='Created By')),
                ('guardian', models.ForeignKey(blank=True, help_text="Auto-filled from student's guardian", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='students.guardian', verbose_name='Guardian')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession', verbose_name='Academic Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student', verbose_name='Student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm', verbose_name='Academic Term')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Receipt Number')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bank_deposit', 'Bank Deposit'), ('pos', 'POS'), ('online', 'Online Payment'), ('remita', 'Remita'), ('cheque', 'Cheque')], max_length=50, verbose_name='Payment Method')),
                ('date_paid', models.DateField(default=django.utils.timezone.now, verbose_name='Date Paid')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_date', models.DateTimeField(blank=True, null=True, verbose_name='Verified Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff', verbose_name='Created By')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.invoice', verbose_name='Invoice')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_receipts', to='staffs.staff', verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-date_paid', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tuition Fee')),
                ('development_levy', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Development Levy')),
                ('sports_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sports Fee')),
                ('library_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Library Fee')),
                ('laboratory_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Laboratory Fee')),
                ('other_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Other Fees')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='corecode.studentclass', verbose_name='Class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff', verbose_name='Created By')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession', verbose_name='Academic Session')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm', verbose_name='Term')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['session', 'term', 'class_fee'],
                'unique_together': {('class_fee', 'session', 'term')},
            },
        ),
    ]
