# Generated by Django 5.0 on 2026-01-31 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('corecode', '0001_initial'),
        ('staffs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='students/bulkupload/')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Chief', 'Chief'), ('Alhaji', 'Alhaji'), ('Hajiya', 'Hajiya')], max_length=20)),
                ('surname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('other_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('relationship', models.CharField(choices=[('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Relative', 'Relative'), ('Guardian', 'Legal Guardian'), ('Other', 'Other')], default='Parent', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guardians/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'ordering': ['surname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('admission', 'Admission System'), ('import', 'Bulk Import'), ('migration', 'Data Migration')], default='manual', max_length=20, verbose_name='Creation Method')),
                ('student_number', models.CharField(editable=False, help_text='Auto-generated student number', max_length=50, unique=True, verbose_name='Student ID')),
                ('surname', models.CharField(max_length=200, verbose_name='Surname')),
                ('firstname', models.CharField(max_length=200, verbose_name='First Name')),
                ('other_name', models.CharField(blank=True, max_length=200, verbose_name='Other Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('mobile_number', models.CharField(blank=True, max_length=20, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Medical Conditions')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('passport', models.ImageField(blank=True, upload_to='students/passports/', verbose_name='Passport Photo')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], default='inactive', max_length=20, verbose_name='Status')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Admission Date')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Graduation Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_link', to='admissions.admissionapplication', verbose_name='Admission Record')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff', verbose_name='Created By')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.studentclass', verbose_name='Current Class')),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.academicsession', verbose_name='Current Session')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.guardian', verbose_name='Guardian/Parent')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['student_number', 'surname', 'firstname'],
                'permissions': [('activate_student', 'Can activate students'), ('deactivate_student', 'Can deactivate students')],
            },
        ),
        migrations.CreateModel(
            name='PromotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_from', to='corecode.studentclass')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_to', to='corecode.studentclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-promoted_at'],
            },
        ),
    ]
