# Generated by Django 5.0 on 2026-02-05 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentbulkupload',
            options={'ordering': ['-date_uploaded'], 'verbose_name': 'Student Bulk Upload', 'verbose_name_plural': 'Student Bulk Uploads'},
        ),
        migrations.AddField(
            model_name='guardian',
            name='last_welcome_email_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Welcome Email'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='user_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='User Created At'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='user_creation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='User Creation Status'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='user_creation_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Creation Task ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='activation_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Activation Task ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_activation_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Activation Check'),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='current_status_message',
            field=models.CharField(blank=True, max_length=500, verbose_name='Current Status'),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='processing_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processing Completed'),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='processing_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processing Started'),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='progress_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress %'),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='records_created',
            field=models.IntegerField(default=0, verbose_name='Records Created'),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='records_failed',
            field=models.IntegerField(default=0, verbose_name='Records Failed'),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='records_processed',
            field=models.IntegerField(default=0, verbose_name='Records Processed'),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=255, null=True, verbose_name='Task ID'),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='task_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Task Status'),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='total_records',
            field=models.IntegerField(default=0, verbose_name='Total Records'),
        ),
    ]
