# Generated by Django 5.0.1 on 2026-01-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('admission', 'Admission System'), ('import', 'Bulk Import')], default='manual', max_length=20),
        ),
    ]
