# Generated by Django 5.0.1 on 2026-01-17 06:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_remove_admissionapplication_student_and_more'),
        ('corecode', '0005_siteconfig_account_name_siteconfig_account_number_and_more'),
        ('staffs', '0002_auto_20201124_0614'),
        ('students', '0003_student_created_via'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_number', 'surname', 'firstname'], 'permissions': [('activate_student', 'Can activate students'), ('deactivate_student', 'Can deactivate students')], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_admission',
        ),
        migrations.RemoveField(
            model_name='student',
            name='others',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_mobile_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Admission Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_link', to='admissions.admissionapplication', verbose_name='Admission Record'),
        ),
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Allergies'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.academicsession', verbose_name='Current Session'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Graduation Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True, verbose_name='Medical Conditions'),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], default='inactive', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=django.utils.timezone.now, editable=False, help_text='Auto-generated student number', max_length=50, unique=True, verbose_name='Student ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('admission', 'Admission System'), ('import', 'Bulk Import'), ('migration', 'Data Migration')], default='manual', max_length=20, verbose_name='Creation Method'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.studentclass', verbose_name='Current Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Other Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, upload_to='students/passports/', verbose_name='Passport Photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='studentbulkupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Chief', 'Chief'), ('Alhaji', 'Alhaji'), ('Alhaja', 'Alhaja')], max_length=20)),
                ('surname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('other_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('relationship', models.CharField(choices=[('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Relative', 'Relative'), ('Guardian', 'Legal Guardian'), ('Other', 'Other')], default='Parent', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guardians/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'ordering': ['surname', 'firstname'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.guardian', verbose_name='Guardian/Parent'),
        ),
    ]
