# Generated by Django 5.0.1 on 2026-01-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='admission_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='admission_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='admissions_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='payment_instructions',
            field=models.TextField(blank=True),
        ),
    ]
