# Generated by Django 5.0 on 2026-01-31 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, help_text='Auto-generated application number', max_length=50, unique=True)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_address', models.TextField()),
                ('guardian_relationship', models.CharField(choices=[('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Relative', 'Relative'), ('Guardian', 'Legal Guardian'), ('Other', 'Other')], default='Parent', max_length=50)),
                ('guardian_photo', models.ImageField(blank=True, null=True, upload_to='admissions/guardians/')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('birth_certificate_number', models.CharField(blank=True, help_text='Birth Certificate/Registration Number', max_length=100)),
                ('religion', models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Traditional', 'Traditional'), ('Other', 'Other')], max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('previous_class', models.CharField(blank=True, max_length=100)),
                ('last_report_card', models.FileField(blank=True, null=True, upload_to='admissions/report_cards/')),
                ('medical_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('doctor_phone', models.CharField(blank=True, max_length=20)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='admissions/students/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('accepted', 'Accepted by Guardian')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number (e.g., Remita RRR, bank teller)', max_length=100)),
                ('payment_verified', models.BooleanField(default=False)),
                ('payment_verified_date', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Application fee amount in Naira', max_digits=10)),
                ('payment_channel', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('bank_deposit', 'Bank Deposit'), ('pos', 'POS'), ('online', 'Online Payment'), ('remita', 'Remita'), ('cash', 'Cash')], max_length=50)),
                ('payment_receipt', models.FileField(blank=True, help_text='Upload payment receipt (optional)', null=True, upload_to='admissions/payment_receipts/')),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('capacity_full', 'Class Capacity Full'), ('academic_requirements', 'Academic Requirements Not Met'), ('age_requirement', 'Age Requirement Not Met'), ('documents_incomplete', 'Incomplete Documents'), ('interview_failed', 'Failed Interview/Assessment'), ('behavioral_issues', 'Previous Behavioral Issues'), ('financial', 'Financial Considerations'), ('other', 'Other Reasons')], max_length=100)),
                ('rejection_details', models.TextField(blank=True)),
                ('admission_letter_sent', models.BooleanField(default=False)),
                ('admission_letter_sent_date', models.DateTimeField(blank=True, null=True)),
                ('guardian_accepted', models.BooleanField(default=False)),
                ('guardian_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('waitlist_position', models.PositiveIntegerField(blank=True, null=True)),
                ('waitlist_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to='corecode.studentclass')),
                ('admission_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to='corecode.academicsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applications', to='staffs.staff')),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-application_date', '-created_at'],
                'permissions': [('verify_payment', 'Can verify payment references'), ('review_application', 'Can review admission applications'), ('make_admission_decision', 'Can approve/reject applications'), ('manage_waitlist', 'Can manage waitlisted applications')],
            },
        ),
    ]
