# Generated by Django 5.0.1 on 2026-01-16 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
        ('staffs', '0002_auto_20201124_0614'),
        ('students', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, help_text='Auto-generated application number', max_length=50, unique=True)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_address', models.TextField()),
                ('guardian_relationship', models.CharField(choices=[('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Relative', 'Relative'), ('Guardian', 'Legal Guardian'), ('Other', 'Other')], default='Parent', max_length=50)),
                ('guardian_photo', models.ImageField(blank=True, null=True, upload_to='admissions/guardians/')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('birth_certificate_number', models.CharField(blank=True, help_text='Birth Certificate/Registration Number', max_length=100)),
                ('religion', models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Traditional', 'Traditional'), ('Other', 'Other')], max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('previous_class', models.CharField(blank=True, max_length=100)),
                ('last_report_card', models.FileField(blank=True, null=True, upload_to='admissions/report_cards/')),
                ('medical_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('doctor_phone', models.CharField(blank=True, max_length=20)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='admissions/students/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number (e.g., Remita RRR)', max_length=100)),
                ('payment_verified', models.BooleanField(default=False)),
                ('payment_verified_date', models.DateTimeField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to='corecode.studentclass')),
                ('admission_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to='corecode.academicsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applications', to='staffs.staff')),
                ('payment_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='staffs.staff')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='staffs.staff')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to='students.student')),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-application_date', '-created_at'],
            },
        ),
    ]
