# Generated by Django 5.0.1 on 2026-01-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionapplication',
            options={'ordering': ['-application_date', '-created_at'], 'permissions': [('verify_payment', 'Can verify payment references'), ('review_application', 'Can review admission applications'), ('make_admission_decision', 'Can approve/reject applications')], 'verbose_name': 'Admission Application', 'verbose_name_plural': 'Admission Applications'},
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Application fee amount in Naira', max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_channel',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('bank_deposit', 'Bank Deposit'), ('pos', 'POS'), ('online', 'Online Payment'), ('remita', 'Remita'), ('cash', 'Cash')], max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='Upload payment receipt (optional)', null=True, upload_to='admissions/payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment reference number (e.g., Remita RRR, bank teller)', max_length=100),
        ),
    ]
