# Generated by Django 5.0 on 2026-01-31 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('staffs', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='created_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application_link', to='students.student', verbose_name='Created Student'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_applications', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='admissionreviewlog',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='admissions.admissionapplication'),
        ),
        migrations.AddField(
            model_name='admissionreviewlog',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff'),
        ),
    ]
