# Generated by Django 5.0.1 on 2026-01-16 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_admissionapplication_options_and_more'),
        ('staffs', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionapplication',
            options={'ordering': ['-application_date', '-created_at'], 'permissions': [('verify_payment', 'Can verify payment references'), ('review_application', 'Can review admission applications'), ('make_admission_decision', 'Can approve/reject applications'), ('manage_waitlist', 'Can manage waitlisted applications')], 'verbose_name': 'Admission Application', 'verbose_name_plural': 'Admission Applications'},
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='admission_letter_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='admission_letter_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_applications', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='rejection_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('capacity_full', 'Class Capacity Full'), ('academic_requirements', 'Academic Requirements Not Met'), ('age_requirement', 'Age Requirement Not Met'), ('documents_incomplete', 'Incomplete Documents'), ('interview_failed', 'Failed Interview/Assessment'), ('behavioral_issues', 'Previous Behavioral Issues'), ('financial', 'Financial Considerations'), ('other', 'Other Reasons')], max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='waitlist_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='waitlist_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('accepted', 'Accepted by Guardian')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AdmissionReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='admissions.admissionapplication')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
