# Generated by Django 5.0.1 on 2026-01-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_admissionapplication_options_and_more'),
        ('students', '0003_student_created_via'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionapplication',
            name='student',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='created_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application_link', to='students.student', verbose_name='Created Student'),
        ),
    ]
